name: Run static analysis

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon'
      - '.github/workflows/run-static-analysis.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, redis, relay
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Run static analysis
        run: composer analyse
